"""add_patient_id_unique

Revision ID: cb8e5c4dbe08
Revises: e91a3c2d4f80
Create Date: 2026-05-29 20:15:59.086401
"""
from alembic import op
import sqlalchemy as sa


revision = 'cb8e5c4dbe08'
down_revision = 'e91a3c2d4f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
