"""add_patient_fields_to_cases

Revision ID: d74166550db2
Revises: 0001_initial
Create Date: 2026-05-26 13:42:00.671363
"""
from alembic import op
import sqlalchemy as sa


revision = 'd74166550db2'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('patient_id', sa.String(length=80), nullable=True))
    op.add_column('cases', sa.Column('patient_name', sa.String(length=120), nullable=True))
    op.add_column('cases', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('cases', sa.Column('exam_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('sonologist_note', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('reviewer_note', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('submitted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'submitted')
    op.drop_column('cases', 'reviewer_note')
    op.drop_column('cases', 'sonologist_note')
    op.drop_column('cases', 'exam_date')
    op.drop_column('cases', 'gender')
    op.drop_column('cases', 'age')
    op.drop_column('cases', 'patient_name')
    op.drop_column('cases', 'patient_id')
    # ### end Alembic commands ###
